services:
  - mysql

sudo: required

# testing
language: php
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - hhvm
sudo: false
env:
addons:
  apt:
    packages:
      - nodejs
before_script:
  - composer install
  - php artisan migrate
  - php artisan db:seed

script:
  - phpunit
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  
# code coverage
before_install:
  - pip install --user codecov
  - mysql -e "create database IF NOT EXISTS laravel5_test;" -uroot
  - mysql -e "create database IF NOT EXISTS test;" -uroot
after_success:
    - bash <(curl -s https://codecov.io/bash)
