services:
  - mysql                                                           # Install mysql server

# testing
language: php                                                       # determinate the programming language
php:
  - "5.5"                                                           # Test for the php 5.5 version
  - "5.6"                                                           # Test for the php 5.6 version
  # - "7.0"
  # - hhvm                                                          # Test for HHVM
sudo: false                                                         # Disable sudo permission
env:
addons:                                                             # Install nodeJS 
  apt:
    packages:
      - nodejs
before_script:
  - composer install                                                # Install the project trough composer?
  - php artisan migrate                                             # Create the database tables.
  - php artisan db:seed                                             # Insert rows in the database
  - npm install -g

script:
  - phpunit --group all                                             # Run phpunit
  - vendor/bin/phpunit --coverage-clover=coverage.xml               # Calculate coverage
  
# code coverage
before_install:
  - pip install --user codecov
  - mysql -e "create database IF NOT EXISTS testing;" -uroot        # Create database laravel5_test for phpunit
  - mysql -e "create database IF NOT EXISTS test;" -uroot           # Create database test for production 
after_success:
    - bash <(curl -s https://codecov.io/bash)                       # Push statistics to http://www.codecov.io

notifications:
  slack: rientjeteen:hcIaSgQATDZWGmX3VjmSqQ9g                       # Push Travis CI notification to slack.
